export const queryKeys = {
  jobs: (filters?: Record<string, unknown>) => filters ? ['jobs', filters] as const : ['jobs'] as const,
  job: (id: string) => ['jobs', id] as const,
  companies: (page?: number) => page !== undefined ? ['companies', page] as const : ['companies'] as const,
  candidateProfile: () => ['candidate', 'profile'] as const,
  candidateApplications: (page?: number) => page !== undefined ? ['candidate', 'applications', page] as const : ['candidate', 'applications'] as const,
  candidateSavedJobs: (page?: number) => page !== undefined ? ['candidate', 'saved-jobs', page] as const : ['candidate', 'saved-jobs'] as const,
  employerProfile: () => ['employer', 'profile'] as const,
  employerJobs: (page?: number) => page !== undefined ? ['employer', 'jobs', page] as const : ['employer', 'jobs'] as const,
  employerJobApplications: (jobId: string, page?: number) => page !== undefined ? ['employer', 'jobs', jobId, 'applications', page] as const : ['employer', 'jobs', jobId, 'applications'] as const,
  adminStats: () => ['admin', 'stats'] as const,
  adminJobs: (params?: Record<string, unknown>) => params ? ['admin', 'jobs', params] as const : ['admin', 'jobs'] as const,
  adminUsers: (params?: Record<string, unknown>) => params ? ['admin', 'users', params] as const : ['admin', 'users'] as const,
  employerTemplates: () => ['employer', 'templates'] as const,
  company: (id: string) => ['company', id] as const,
  companyJobs: (employerId: string, page?: number) => page !== undefined ? ['company', employerId, 'jobs', page] as const : ['company', employerId, 'jobs'] as const,
  candidateSearch: (params?: Record<string, unknown>) => params ? ['employer', 'candidates', params] as const : ['employer', 'candidates'] as const,
  adminReports: (params?: Record<string, unknown>) => params ? ['admin', 'reports', params] as const : ['admin', 'reports'] as const,
  adminLogs: (params?: Record<string, unknown>) => params ? ['admin', 'logs', params] as const : ['admin', 'logs'] as const,
  candidateJobAlerts: () => ['candidate', 'job-alerts'] as const,
  notifications: (page?: number) => page !== undefined ? ['notifications', page] as const : ['notifications'] as const,
  notificationsUnreadCount: () => ['notifications', 'unread-count'] as const,
  recommendedJobs: (limit?: number) => limit !== undefined ? ['candidate', 'recommended-jobs', limit] as const : ['candidate', 'recommended-jobs'] as const,
  followedCompanies: (page?: number) => page !== undefined ? ['candidate', 'followed-companies', page] as const : ['candidate', 'followed-companies'] as const,
  followStatus: (employerId: string) => ['candidate', 'following', employerId] as const,
  applicationTimeline: (appId: string) => ['candidate', 'applications', appId, 'timeline'] as const,
  candidateCvs: () => ['candidate', 'cvs'] as const,
};
